server:
  port: 9000

---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
---

spring:
  cloud:
    gateway:
    httpclient:
      connect-timeout: 1000
      response-timeout: 300s
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: false
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        # Inventory Service Routes
        - id: inventory-service-all
          uri: lb://spring-inventory-service
          predicates:
            - Path=/inventory/**
#          filters:
#            - RewritePath=/inventory/(?<segment>.*), /inventory/${segment}
#            - name: CircuitBreaker
#              args:
#                name: inventoryCircuitBreaker
#                fallbackUri: forward:/fallback/inventory

#        # Specific Product Routes
#        - id: inventory-get-products
#          uri: lb://spring-inventory-service
#          predicates:
#            - Path=/api/products
#            - Method=GET
#          filters:
#            - RewritePath=/api/products, /api/inventory/products
---

# Resilience4j circuit breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      billingCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
